Sync again. Couple more tweaks for my env

diff --git a/dot_dotfiles/bin/executable_dotfiles b/dot_dotfiles/bin/executable_dotfiles
--- a/dot_dotfiles/bin/executable_dotfiles
+++ b/dot_dotfiles/bin/executable_dotfiles
@@ -41,20 +41,35 @@ function link {
 
 # Fix terminal config
 function fixterm {
-    if [[ $TERM == "xterm-kitty" && $(uname -s) == "Darwin" && ! -d $HOME/.terminfo/78/xterm-kitty ]]; then
-        local tmpfile=$(mktemp /tmp/dotfiles.XXXXXX)
-        infocmp xterm-kitty > $tmpfile
-        tic -x -o $HOME/.terminfo $tmpfile &> /dev/null
-        rm $tmpfile
+    if [[ $TERM == "xterm-kitty" ]]; then
+        infocmp &> /dev/null
+        if (( $? )); then
+            local tmpfile=$(mktemp /tmp/dotfiles.XXXXXX)
+            curl --silent -o $tmpfile https://raw.githubusercontent.com/kovidgoyal/kitty/master/terminfo/x/xterm-kitty
+            tic -x -o $HOME/.terminfo $tmpfile &> /dev/null
+            rm $tmpfile
+            logSub "Installed kitty terminfo"
+        fi
+    fi
+
+    if [[ $TERM == "wezterm" ]]; then
+        infocmp &> /dev/null
+        if (( $? )); then
+            local tmpfile=$(mktemp /tmp/dotfiles.XXXXXX)
+            curl --silent -o $tmpfile https://raw.githubusercontent.com/wez/wezterm/master/termwiz/data/wezterm.terminfo
+            tic -x -o $HOME/.terminfo $tmpfile &> /dev/null
+            rm $tmpfile
+            logSub "Installed wezterm terminfo"
+        fi
     fi
 
     # Fix terminal definition so C-H works properly in neovim
-    kbs=$(infocmp $TERM | grep -o 'kbs=[^,]\+')
+    kbs=$(infocmp | grep -o 'kbs=[^,]\+')
     if [[ $kbs =~ "kbs=^[hH]" ]]; then
-        logSub "Fixing backspace code in terminfo..."
         infocmp $TERM | sed 's/kbs=^[hH]/kbs=\\177/' > /tmp/$TERM.ti
         tic /tmp/$TERM.ti
         rm /tmp/$TERM.ti
+        logSub "Fixed backspace code in terminfo"
     fi
 }
 
@@ -140,6 +155,20 @@ function dotfiles-buildtools {
         if (( $? )); then
             err "Error installing build tools"
             err $out
+        fi
+    fi
+}
+
+# Install terminal fonts
+function dotfiles-fonts {
+    log "Installing terminal fonts..."
+
+    if [[ $OSTYPE == darwin* ]]; then
+        local fonts
+        fonts=($HOME/Library/Fonts/Symbols-1000*(NY1))
+        if (( ${#fonts} == 0 )) then
+            curl --silent -o "$HOME/Library/Fonts/Symbols-1000-em Nerd Font Complete.ttf" "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/src/glyphs/Symbols-1000-em%20Nerd%20Font%20Complete.ttf"
+            logSub "Installed Symbols-1000-em Nerd Font Complete"
         fi
     fi
 }
@@ -237,21 +266,18 @@ function dotfiles-brew {
         'asdf'        # version manager
         'bash'        # update from system stock version
         'bat'         # better cat
-        'deno'        # TS runtime
         'direnv'      # environment manager
         'fd'          # file finder
         'fzf'         # fuzzy finder
         'git'         # update from system stock git
         'git-delta'   # prettier git diffs
         'jq'          # command line JSON processor
-        'neovim'      # editor
-        'node'        # Node.js
         'pdm'         # python package manager
-        'python'      # default python
+        'python@3.9'  # default python
         'ripgrep'     # better grep
+        'stylua'      # lua formatter
         'tig'         # terminal git ui
-        'tmux'        # terminal manager
-        'zsh'         # newer zsh
+        'tmux'        # terminal multiplexer
     )
 
     brew_casks=""
@@ -261,6 +287,7 @@ function dotfiles-brew {
             'font-jetbrains-mono-nerd-font'
             'kitty'
             'phoenix'
+            '1password-cli'
         )
 
         taps=($(brew tap))
@@ -300,6 +327,84 @@ function dotfiles-brew {
     # Remove git's included zsh completions in favor of the system completions
     if [[ -f $HOMEBREW_BASE/share/zsh/site-functions/_git ]]; then
         rm -f $HOMEBREW_BASE/share/zsh/site-functions/_git
+    fi
+
+    # Update 1password-cli zsh completions
+    if (( $+commands[op] )); then
+        op completion zsh >! $ZDATADIR/functions/_op
+    fi
+}
+
+# Install or update deno
+function dotfiles-deno {
+    log "Updating deno..."
+
+    local out=""
+    local version=""
+
+    if (( ! $+commands[deno] )); then
+        logSub "Installing..."
+        out=$(curl -fsSL https://deno.land/x/install/install.sh | sh)
+        if (( $? )); then
+            err "Error installing deno"
+            err $out
+        fi
+        rehash
+    else
+        out=$(deno upgrade)
+        if [[ ! $out =~ "is the most recent release" ]]; then
+            version=$(deno --version | grep 'deno [0-9]' | awk '{print $2}')
+            logSub "Installed version $version"
+        fi
+    fi
+
+    deno completions zsh >! $ZDATADIR/functions/_deno
+}
+
+# Install or update bun
+function dotfiles-bun {
+    log "Updating bun..."
+
+    local out=""
+    local version=""
+
+    if (( ! $+commands[bun] )); then
+        logSub "Installing..."
+        out=$(curl https://bun.sh/install | bash)
+        if (( $? )); then
+            err "Error installing bun"
+            err $out
+        fi
+        rehash
+    else
+        local message=$(bun upgrade 2>&1)
+        if [[ $message == "Congrats *" ]]; then
+            logSub "Upgraded bun to v$(bun -v)"
+        fi
+    fi
+
+    bun completions > /dev/null
+
+    # remove completion line added to zshrc
+    local zshrc=$HOME/.dotfiles/home/zshrc
+    local line=$(grep -n '# bun completions' $HOME/.zshrc | cut -f1 -d:)
+    if [[ -n $line ]]; then
+        local start
+        (( start = $line - 1 ))
+        local end
+        (( end = $line + 1 ))
+        sed -i "" "${start},${end}d" "$zshrc"
+    fi
+}
+
+# Install or update rust
+function dotfiles-rust {
+    if (( ! $+commands[rustup] )); then
+        log "Installing rust..."
+        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
+    else
+        log "Updating rust..."
+        rustup update
     fi
 }
 
@@ -345,10 +450,6 @@ function dotfiles-python {
         err "Error updating packages"
         err $out
     fi
-
-    mkdir -p $ZCOMPDIR
-    pdm completion > $ZCOMPDIR/_pdm
-    logSub "Installed pdm completions"
 }
 
 # Update global npm packages
@@ -394,7 +495,6 @@ function dotfiles-node {
 
     local desired_packages=(
         eslint_d
-        prettier
         neovim
     )
 
@@ -498,34 +598,18 @@ function dotfiles-asdf {
     done
 
     # Update all plugins
-    logSub "Updating plugins..."
     for plugin in $(asdf plugin list); do
         if ((! $installed_plugins[(Ie)$plugin])); then
-            asdf plugin update $plugin > /dev/null
+            local out=$(asdf plugin update $plugin)
+            if [[ ! $out =~ 'Your branch is up to date' ]]; then
+                logSub "Updated $plugin"
+            fi
         fi
     done
 
     # Setup the "system" install for asdf-direnv
-    if [[ -d $ASDF_DATA_DIR ]]; then
-        # For `asdf exec direnv` to work, asdf needs a direnv shim. For it to
-        # be able to create that, *some* installed version of direnv needs a
-        # binary. If we only want to use the system install, we have to create
-        # a link to the system direnv binary in installs/direnv/system/bin.
-        if [[ ! -L $ASDF_DATA_DIR/installs/direnv/system/bin/direnv ]]; then
-            mkdir -p $ASDF_DATA_DIR/installs/direnv/system/bin
-            ln -s $HOMEBREW_BASE/bin/direnv $ASDF_DATA_DIR/installs/direnv/system/bin
-            asdf reshim
-            logSub "Created direnv link"
-        fi
-
-        # asdf needs a directory to create environments for each installed
-        # version. 
-        if [[ ! -d $ASDF_DATA_DIR/installs/direnv/system/env ]]; then
-            mkdir -p $ASDF_DATA_DIR/installs/direnv/system/env
-            logSub "Created direnv environment directory"
-        fi
-
-        asdf global direnv system
+    if [[ ! -d $CONFIGDIR/asdf-direnv ]]; then
+        asdf direnv setup --shell zsh --version system
     fi
 }
 
@@ -545,6 +629,9 @@ if [[ -n $1 ]]; then
         echo '    asdf           Update asdf plugins, install defaults'
         echo '    bat            Rebuild bat theme and filetype cache'
         echo '    brew           Update brew packages, install defaults'
+        echo '    deno           Update deno'
+        echo '    fonts          Install terminal fonts'
+        echo '    rust           Update rust'
         echo '    home           Update dotfiles and home directories, fixup terminfo database'
         echo '    launchd        Link and bootstrap launchd scripts'
         echo '    node           Update global node packages, install defaults'
@@ -563,8 +650,12 @@ else
     dotfiles-health
     dotfiles-home
     dotfiles-brew
+    dotfiles-fonts
     dotfiles-buildtools
     dotfiles-asdf
+    dotfiles-deno
+    dotfiles-bun
+    dotfiles-rust
 
     dotfiles-zsh
     dotfiles-python
